# Generated by Django 6.0.7 on 2026-08-11 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('upi_id', models.CharField(blank=True, max_length=256)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('kyc_status', models.CharField(default='Not Verified', max_length=20)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=10)),
                ('aadhaar', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=15)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('ifsc', models.CharField(blank=True, max_length=15)),
                ('banks', models.JSONField(blank=True, default=list)),
                ('aadhaar_mobile_linked', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('returns', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Pending Bank Transfer', 'Pending Bank Transfer'), ('Confirmed', 'Confirmed'), ('Failed', 'Failed')], default='Pending', max_length=30)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('virtual_account', models.JSONField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('processing_end', models.DateTimeField()),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('ifsc', models.CharField(blank=True, max_length=15)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('method', models.CharField(default='NEFT/RTGS/IMPS', max_length=30)),
                ('utr', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='app.userprofile')),
            ],
        ),
    ]
